### PR TITLE
Change Server Description and Favicon

### PR DESCRIPTION
**Pull request by dave-tucker**
Add OnServerPing plugin hook to return a better description and favicon
when the server is pinged

screenshot 2015-11-18 01 36 29

Signed-off-by: Dave Tucker <dt@docker.com>

### CODE REVIEW

**Comment by mheiniger** [comment]
good idea

**Comment by aduermael** [comment]
Just tested it, it's great to have an icon! :+1: 
LGTM (cc @gdevillele)

**Comment by gdevillele** [comment]
LGTM 🐙

**Comment by gdevillele** [comment]
Thank you @dave-tucker ;)

**Pull request merged**
