### PR TITLE
Add dockerignore

### PR DESCRIPTION
**Pull request by dave-tucker**
Shave a few MBs off the build context

Signed-off-by: Dave Tucker <dt@docker.com>

### CODE REVIEW

**Comment by gdevillele** [comment]
good idea! :)

LGTM

**Comment by gdevillele** [comment]
can you ignore also
- /CONTRIBUTING.md
- /docs (⚠️ except the icon used by the server: /docs/img/logo64x64.png)
- /LICENSE
- /MAINTAINERS
- /README.md

**Comment by dave-tucker** [comment]
@gdevillele added your suggestions! 
Total reduction is from 109.6MB to 84.64MB

**Comment by gdevillele** [comment]
LGTM :+1:

**Pull request merged**
