### PR TITLE
Implement Explosions!

### LINKED ISSUE #31: Proposal: Destroying containers should make them explode
Because explosions are way cooler than the container disappearing!

### PR DESCRIPTION
**Pull request by dave-tucker**
Fixes #31

### CODE REVIEW

**Comment by dave-tucker** [comment]
Hi @NiLSPACE - having some issues with explosions :bomb: 
As far as I can tell, my explosion happens (both the Exploding and Exploded) hooks get triggered... but I don't hear an explosion sound, nor do any of the blocks get destroyed. I thought I might be doing something wrong, but my explosion code looks pretty similar to one of your plugins https://github.com/NiLSPACE/Magic/blob/master/Magic/FireDragon.lua#L14

Am I missing something obvious?

**Comment by NiLSPACE** [comment]
You do have the right world? You're currently doing it on the default world. Perhaps you have another world where the explosion should be happening.

Even stranger is that when I manually try to cause an explosion my client just stops rendering the terrain. TNT works fine though. @madmaxoft do you know what could be going on here?

**Comment by dave-tucker** [comment]
@NiLSPACE my bad. Had my X and Y in a muddle... now the :boom: is rather satisfying

boom

**Comment by dave-tucker** [comment]
:boom: 

To make this work we don't **actually** have a real explosion because:
- Pushback will force you off the edge of the platform
- We can't prevent the floor from being blown up AND remove all of the container blocks

The solution was to simulate an explosion by broadcasting the correct sound and particle effects and to manually remove the blocks we need.
I also made it so the levers + signs don't hang around after the container is removed :smile: 

boom2

/cc @gdevillele @aduermael - ready for review

**Comment by aduermael** [comment]
@dave-tucker THIS IS AWESOME! :+1:

**Comment by gdevillele** [comment]
and then @dave-tucker 's magic happened ...

👻

**Comment by joshmanders** [comment]
I literally can't even right now.

**Comment by victort** [comment]
:+1:

**Comment by aduermael** [comment]
Tested it, LGTM! :+1:

**Pull request merged**
