### PR TITLE
Refactor to single Go daemon and add some infrastructure

### PR DESCRIPTION
**Pull request by dave-tucker**
- Refactor proxy and setup to single `dockercraft` daemon
- Automatically download the latest Docker release, remove the Docker
  binary from the repo
- Use Golang 1.6
- Update to Docker 1.11.1 in the Dockerfile
- Dockerize all the testing
- Add test targets for checking our golang code
- Build and Serve targets for testing changes
- Address comments from go fmt and go lint
- Add simple circle.yml for CircleCI

Signed-off-by: Dave Tucker <dt@docker.com>

### CODE REVIEW

**Comment by dave-tucker** [comment]
For vendoring, I'm currently using the very cool [gvt](https://github.com/FiloSottile/gvt), but anything that dumps code in to the `/vendor` directory is fair game - we aren't tied to anything in particular

**Comment by dave-tucker** [comment]
/cc @aduermael @gdevillele I had some time while on vacation last week!
This PR should simplify development a lot - next step is to port over my `docker-machine` changes!

**Comment by dave-tucker** [comment]
Also this overlaps with #52

**Comment by gdevillele** [comment]
@dave-tucker cool! Don't worry about #52. We will probably hand pick what we want from it and drop that PR.

**Comment by gdevillele** [comment]
@dave-tucker amazing PR overall!!

Could you please update the line 42 in the Makefile please?
from
`-p 25566:25565 \` 
to 
`-p 25565:25565 \`

Thank you.

**Comment by dave-tucker** [comment]
@gdevillele done! thanks for the review!

**Comment by dave-tucker** [comment]
Thanks @gdevillele for helping backport those changes from #65! You're a 🌟

**Pull request merged**
