### PR TITLE
Basic Support for Docker Machine

### LINKED ISSUE #49: Proposal: Docker Machine Integration
Following on from the discussion in #19, here is a mock up of what integration with Docker Machine could look like.

The player gets dropped in to a lobby when connecting:

screenshot 2015-12-06 19 01 57

On each of the portals is a sign that gives the name of the "Machine" it represents.
Stepping through the portal will teleport the player to the world where they can interact with that machine, much like the default Dockercraft world today... The only difference being that we have a portal that will take us "back" to the lobby world.

We'll support two modes of use:

1.  When you bind mount the docker socket, we will create a "default" machine and use the mounted socket to communicate with the Docker API. This is for backwards compatibility.

2. Instead of mounting the one socket, you can mount your entire `.docker` folder which will create a portal for each of your machines
Portals are added in a straight line, first to the left of the existing portals, then to the right. This means that the "default" portal will *always* be dead centre and that the line should extend evenly in each direction.

Under the hood, we use `libmachine` to query the list of created machines and to get the necessary certificates to set up a secure API connection over HTTPS.

### PR DESCRIPTION
**Pull request by dave-tucker**
This PR adds basic support for Docker Machine

As [Cuberite doesn't (yet) support dynamic reload](https://forum.cuberite.org/thread-2383.html) of `settings.ini`, the machines that are available when Dockercraft is started are the only ones available...

We mount the users `~/.docker/machine/machines` folder, iterate over it, find machines with an IP address and have a go at connecting to them. This is tested to work with Docker Machine 0.7.0

Full usage is covered in the README but the TL;DR is `/worlds` to see available worlds and `/portal <world>` to change worlds.

This work has exposed a race between the when the proxy is ready to send events and when the Docker plugin is ready to receive them. Hopefully this will be improved by #42 

Depends On #59 
Closes #49

### CODE REVIEW

**Comment by dave-tucker** [comment]
Obligatory GIF demo
machine

**Comment by dave-tucker** [comment]
The shakiness on switching worlds is due to Cuberite getting a list of containers when the player has changed worlds. This can go away once the aforementioned race is fixed as each world will continue to update in the background (i.e with no player logged in)

**Comment by nniiff** [comment]
Sent from Yahoo Mail on Android 
 
  On الاثنين, مايو ٩, ٢٠١٦ at ٤:٢٣ م, Dave Tucker<notifications@github.com> wrote:   
This PR adds basic support for Docker Machine

As Cuberite doesn't (yet) support dynamic reload of settings.ini, the machines that are available when Dockercraft is started are the only ones available...

We mount the users ~/.docker/machine/machines folder, iterate over it, find machines with an IP address and have a go at connecting to them. This is tested to work with Docker Machine 0.7.0

Full usage is covered in the README but the TL;DR is /worlds to see available worlds and /portal <world> to change worlds.

This work has exposed a race between the when the proxy is ready to send events and when the Docker plugin is ready to receive them. Hopefully this will be improved by #42 

Depends On #59 
Closes #49 

You can view, comment on, or merge this pull request online at:

  https://github.com/docker/dockercraft/pull/60

Commit Summary
   
   - Refactor to single Go daemon
   - Intial Docker Machine integration

File Changes
   
   -  M .gitignore (1) 
   -  M Dockerfile (20) 
   -  A Makefile (47) 
   -  M README.md (25) 
   -  A circle.yml (12) 
   -  M docker-compose.yml (4) 
   -  D docker/docker-1.9.1 (0) 
   -  D go/src/github.com/Sirupsen/logrus/.gitignore (1) 
   -  D go/src/github.com/Sirupsen/logrus/.travis.yml (7) 
   -  D go/src/github.com/Sirupsen/logrus/CHANGELOG.md (53) 
   -  D go/src/github.com/Sirupsen/logrus/README.md (356) 
   -  D go/src/github.com/Sirupsen/logrus/entry_test.go (77) 
   -  D go/src/github.com/Sirupsen/logrus/formatter_bench_test.go (98) 
   -  D go/src/github.com/Sirupsen/logrus/formatters/logstash/logstash_test.go (52) 
   -  D go/src/github.com/Sirupsen/logrus/hook_test.go (122) 
   -  D go/src/github.com/Sirupsen/logrus/hooks/bugsnag/bugsnag.go (68) 
   -  D go/src/github.com/Sirupsen/logrus/hooks/bugsnag/bugsnag_test.go (64) 
   -  D go/src/github.com/Sirupsen/logrus/hooks/papertrail/README.md (28) 
   -  D go/src/github.com/Sirupsen/logrus/hooks/papertrail/papertrail.go (55) 
   -  D go/src/github.com/Sirupsen/logrus/hooks/papertrail/papertrail_test.go (26) 
   -  D go/src/github.com/Sirupsen/logrus/hooks/syslog/README.md (39) 
   -  D go/src/github.com/Sirupsen/logrus/hooks/syslog/syslog_test.go (26) 
   -  D go/src/github.com/Sirupsen/logrus/json_formatter_test.go (120) 
   -  D go/src/github.com/Sirupsen/logrus/logrus_test.go (301) 
   -  D go/src/github.com/Sirupsen/logrus/text_formatter_test.go (61) 
   -  D go/src/github.com/Sirupsen/logrus/writer.go (31) 
   -  D go/src/github.com/docker/docker/pkg/units/duration_test.go (46) 
   -  D go/src/github.com/docker/docker/pkg/units/size_test.go (108) 
   -  D go/src/github.com/samalba/dockerclient/.gitignore (22) 
   -  D go/src/github.com/samalba/dockerclient/README.md (98) 
   -  D go/src/github.com/samalba/dockerclient/auth_test.go (15) 
   -  D go/src/github.com/samalba/dockerclient/dockerclient_test.go (241) 
   -  D go/src/github.com/samalba/dockerclient/engine_mock_test.go (245) 
   -  D go/src/github.com/samalba/dockerclient/mockclient/mock_test.go (32) 
   -  D go/src/gosetup/main.go (67) 
   -  A machines.go (183) 
   -  A main.go (201) 
   -  R proxy.go (197) 
   -  A setup.go (65) 
   -  D start.sh (9) 
   -  A vendor/github.com/Jeffail/gabs/LICENSE (19) 
   -  A vendor/github.com/Jeffail/gabs/gabs.go (645) 
   -  R vendor/github.com/Sirupsen/logrus/LICENSE (0) 
   -  R vendor/github.com/Sirupsen/logrus/doc.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/entry.go (2) 
   -  R vendor/github.com/Sirupsen/logrus/examples/basic/basic.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/examples/hook/hook.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/exported.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/formatter.go (15) 
   -  R vendor/github.com/Sirupsen/logrus/formatters/logstash/logstash.go (29) 
   -  R vendor/github.com/Sirupsen/logrus/hooks.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/hooks/syslog/syslog.go (11) 
   -  A vendor/github.com/Sirupsen/logrus/hooks/test/test.go (67) 
   -  R vendor/github.com/Sirupsen/logrus/json_formatter.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/logger.go (6) 
   -  R vendor/github.com/Sirupsen/logrus/logrus.go (47) 
   -  R vendor/github.com/Sirupsen/logrus/terminal_bsd.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/terminal_linux.go (0) 
   -  R vendor/github.com/Sirupsen/logrus/terminal_notwindows.go (4) 
   -  A vendor/github.com/Sirupsen/logrus/terminal_solaris.go (15) 
   -  R vendor/github.com/Sirupsen/logrus/terminal_windows.go (4) 
   -  R vendor/github.com/Sirupsen/logrus/text_formatter.go (8) 
   -  A vendor/github.com/Sirupsen/logrus/writer.go (53) 
   -  A vendor/github.com/davecgh/go-spew/spew/LICENSE (13) 
   -  A vendor/github.com/davecgh/go-spew/spew/bypass.go (151) 
   -  A vendor/github.com/davecgh/go-spew/spew/bypasssafe.go (37) 
   -  A vendor/github.com/davecgh/go-spew/spew/common.go (341) 
   -  A vendor/github.com/davecgh/go-spew/spew/config.go (297) 
   -  A vendor/github.com/davecgh/go-spew/spew/doc.go (202) 
   -  A vendor/github.com/davecgh/go-spew/spew/dump.go (509) 
   -  A vendor/github.com/davecgh/go-spew/spew/format.go (419) 
   -  A vendor/github.com/davecgh/go-spew/spew/spew.go (148) 
   -  R vendor/github.com/docker/go-units/duration.go (0) 
   -  R vendor/github.com/docker/go-units/size.go (12) 
   -  A vendor/github.com/docker/go-units/ulimit.go (118) 
   -  A vendor/github.com/pmezard/go-difflib/difflib/LICENSE (27) 
   -  A vendor/github.com/pmezard/go-difflib/difflib/difflib.go (772) 
   -  R vendor/github.com/samalba/dockerclient/LICENSE (0) 
   -  R vendor/github.com/samalba/dockerclient/auth.go (7) 
   -  R vendor/github.com/samalba/dockerclient/dockerclient.go (136) 
   -  R vendor/github.com/samalba/dockerclient/example_responses.go (2) 
   -  R vendor/github.com/samalba/dockerclient/examples/events.go (0) 
   -  R vendor/github.com/samalba/dockerclient/examples/stats/stats.go (2) 
   -  R vendor/github.com/samalba/dockerclient/interface.go (12) 
   -  R vendor/github.com/samalba/dockerclient/mockclient/mock.go (23) 
   -  R vendor/github.com/samalba/dockerclient/nopclient/nop.go (16) 
   -  A vendor/github.com/samalba/dockerclient/tls.go (38) 
   -  R vendor/github.com/samalba/dockerclient/types.go (240) 
   -  R vendor/github.com/samalba/dockerclient/utils.go (12) 
   -  A vendor/github.com/stretchr/objx/LICENSE.md (23) 
   -  A vendor/github.com/stretchr/objx/accessors.go (179) 
   -  A vendor/github.com/stretchr/objx/constants.go (13) 
   -  A vendor/github.com/stretchr/objx/conversions.go (117) 
   -  A vendor/github.com/stretchr/objx/doc.go (72) 
   -  A vendor/github.com/stretchr/objx/map.go (222) 
   -  A vendor/github.com/stretchr/objx/mutations.go (81) 
   -  A vendor/github.com/stretchr/objx/security.go (14) 
   -  A vendor/github.com/stretchr/objx/tests.go (17) 
   -  A vendor/github.com/stretchr/objx/type_specific_codegen.go (0) 
   -  A vendor/github.com/stretchr/objx/value.go (0) 
   -  A vendor/github.com/stretchr/testify/assert/LICENCE.txt (0) 
   -  A vendor/github.com/stretchr/testify/assert/LICENSE (0) 
   -  A vendor/github.com/stretchr/testify/assert/assertion_forward.go (0) 
   -  A vendor/github.com/stretchr/testify/assert/assertions.go (0) 
   -  A vendor/github.com/stretchr/testify/assert/doc.go (0) 
   -  A vendor/github.com/stretchr/testify/assert/errors.go (0) 
   -  A vendor/github.com/stretchr/testify/assert/forward_assertions.go (0) 
   -  A vendor/github.com/stretchr/testify/assert/http_assertions.go (0) 
   -  A vendor/github.com/stretchr/testify/mock/LICENCE.txt (0) 
   -  A vendor/github.com/stretchr/testify/mock/LICENSE (0) 
   -  A vendor/github.com/stretchr/testify/mock/doc.go (0) 
   -  A vendor/github.com/stretchr/testify/mock/mock.go (0) 
   -  A vendor/gopkg.in/airbrake/gobrake.v2/LICENSE (0) 
   -  A vendor/gopkg.in/airbrake/gobrake.v2/gobrake.go (0) 
   -  A vendor/gopkg.in/airbrake/gobrake.v2/notice.go (0) 
   -  A vendor/gopkg.in/airbrake/gobrake.v2/notifier.go (0) 
   -  A vendor/gopkg.in/airbrake/gobrake.v2/util.go (0) 
   -  A vendor/gopkg.in/gemnasium/logrus-airbrake-hook.v2/LICENSE (0) 
   -  A vendor/gopkg.in/gemnasium/logrus-airbrake-hook.v2/airbrake.go (0) 
   -  A vendor/manifest (0) 
   -  A world/Plugins/Docker/Info.lua (0) 
   -  I world/Plugins/Docker/config.lua (0) 
   -  I world/Plugins/Docker/container.lua (0) 
   -  I world/Plugins/Docker/docker.lua (0) 
   -  I world/Plugins/Docker/log.lua (0) 
   -  I world/Plugins/Docker/update.lua (0) 
   -  A world/Plugins/Docker/world.lua (0) 
   -  D world/settings.ini (0) 
   -  A world/settings.ini.tmpl (0) 
   -  D world/world/level.dat (0) 
   -  D world/world/region/r.-1.-1.mca (0) 
   -  D world/world/region/r.-1.-1.mcr (0) 
   -  D world/world/region/r.-1.-2.mca (0) 
   -  D world/world/region/r.-1.-2.mcr (0) 
   -  D world/world/region/r.-1.0.mca (0) 
   -  D world/world/region/r.-1.0.mcr (0) 
   -  D world/world/region/r.-1.1.mca (0) 
   -  D world/world/region/r.-1.1.mcr (0) 
   -  D world/world/region/r.0.-1.mca (0) 
   -  D world/world/region/r.0.-1.mcr (0) 
   -  D world/world/region/r.0.-2.mca (0) 
   -  D world/world/region/r.0.-2.mcr (0) 
   -  D world/world/region/r.0.0.mca (0) 
   -  D world/world/region/r.0.0.mcr (0) 
   -  D world/world/region/r.0.1.mca (0) 
   -  D world/world/region/r.0.1.mcr (0) 
   -  D world/world/region/r.1.-1.mca (0) 
   -  D world/world/region/r.1.-1.mcr (0) 
   -  D world/world/region/r.1.-2.mca (0) 
   -  D world/world/region/r.1.-2.mcr (0) 
   -  D world/world/region/r.1.0.mca (0) 
   -  D world/world/region/r.1.0.mcr (0) 
   -  D world/world/region/r.1.1.mca (0) 
   -  D world/world/region/r.1.1.mcr (0) 
   -  D world/world/world.ini (0) 
   -  A world/world_template/level.dat (0) 
   -  A world/world_template/region/r.-1.-1.mca (0) 
   -  A world/world_template/region/r.-1.-1.mcr (0) 
   -  A world/world_template/region/r.-1.-2.mca (0) 
   -  A world/world_template/region/r.-1.-2.mcr (0) 
   -  A world/world_template/region/r.-1.0.mca (0) 
   -  A world/world_template/region/r.-1.0.mcr (0) 
   -  A world/world_template/region/r.-1.1.mca (0) 
   -  A world/world_template/region/r.-1.1.mcr (0) 
   -  A world/world_template/region/r.0.-1.mca (0) 
   -  A world/world_template/region/r.0.-1.mcr (0) 
   -  A world/world_template/region/r.0.-2.mca (0) 
   -  A world/world_template/region/r.0.-2.mcr (0) 
   -  A world/world_template/region/r.0.0.mca (0) 
   -  A world/world_template/region/r.0.0.mcr (0) 
   -  A world/world_template/region/r.0.1.mca (0) 
   -  A world/world_template/region/r.0.1.mcr (0) 
   -  A world/world_template/region/r.1.-1.mca (0) 
   -  A world/world_template/region/r.1.-1.mcr (0) 
   -  A world/world_template/region/r.1.-2.mca (0) 
   -  A world/world_template/region/r.1.-2.mcr (0) 
   -  A world/world_template/region/r.1.0.mca (0) 
   -  A world/world_template/region/r.1.0.mcr (0) 
   -  A world/world_template/region/r.1.1.mca (0) 
   -  A world/world_template/region/r.1.1.mcr (0) 
   -  A world/world_template/world.ini (0) 

Patch Links:
   
   - https://github.com/docker/dockercraft/pull/60.patch
   - https://github.com/docker/dockercraft/pull/60.diff

**Comment by djassain** [comment]
wow

**Pull request closed without merging**
