### PR TITLE
Set game mode to creative

### LINKED ISSUE #3: Avatar dies of hunger long before reaching end of image road.
Description of problem:
I have a lot of containers running, so many in fact that poor Steve simply can't reach the end before dieing from hunger.

`docker version`:
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   76d6bc9
 Built:        Tue Nov  3 21:17:48 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 323
Images: 504
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 528
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: dev
ID: GOB3:F2ZI:DKD6:5T5Q:UBKT:6VFS:NQBG:UHTY:72BR:SMZ7:REM7:OBCJ
Debug mode (server): true
 File Descriptors: 72
 Goroutines: 128
 System Time: 2015-11-17T22:43:50.660412425Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

`uname -a`:
Darwin in5441.et.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64

Environment details (AWS, VirtualBox, physical, etc.):
VirtualBox

How reproducible:
Just don't clean up after yourself for a month or two.

Steps to Reproduce:
1. Don't `docker rm` any containers
2. wait until you have a couple hundred
3. walk of shame

Actual Results:
Hunger kills Steve

Expected Results:
Either hunger could be disabled, or turn docker road into docker shanty town to walk a grid instead of a single long roadway.

Additional info:
Awesome job guys!  This was a lot of fun!

### PR DESCRIPTION
**Pull request by dave-tucker**
Creative mode doesn't implement the hunger mechanic

Fixes #3

Signed-off-by: Dave Tucker <dt@docker.com>

### CODE REVIEW

**Comment by adamjgray** [comment]
:+1:

**Comment by jakesyl** [comment]
:+1:

**Comment by myyk** [comment]
I think monsters should still be a threat while making changes to your docker environment. It's just an occupational hazard we should accept. If there was no risk, why would anyone pay us to do this job?

**Comment by FrenchBen** [comment]
:+1:

**Comment by bennycornelissen** [comment]
@myyk :+1:

**Comment by aduermael** [comment]
LGTM 👍

**Comment by gdevillele** [comment]
Thank you!
LGTM 🐳

**Pull request merged**
