### PR TITLE
[WIP] Adding some project infrastructure

### PR DESCRIPTION
**Pull request by dave-tucker**
- Using Godep for dependencies
- Add Makefile
- Get ready to run CircleCI against every new commit

### CODE REVIEW

**Comment by aduermael** [comment]
@dave-tucker: I'll have a deeper look at this sometime this week. But I don't really like Godep myself...
The experimental vendoring in Go 1.5 is pretty cool, it should turn to non-experimental soon (hopefully). 
Apparently, Godep also requires GO15VENDOREXPERIMENT=1, but then, what is Godep providing on top of experimental vendoring?

**Comment by gdevillele** [comment]
In a general manner, I think the same as @aduermael about go vendoring. I am not 100% sure about what is best for now, but I am quite sure that we should use this new Go vendoring feature, at least when it won't be experimental anymore 😊
It is fine with me of we use it from now on...
About godep, I would be happy to know more about it and why it is eventually a good choice/fit ;)

**Comment by dave-tucker** [comment]
@aduermael @gdevillele I have a love hate relationship with Godep... but in the my last 2 years of gopher'ing, it's been the most dependable tool I could find.

Love:
- It uses the version of a dependency that I have on my $GOPATH
- I use "git checkout" and "godep update github.com/foo/bar" to bump a version of a dependency
- I can set my $GOPATH to the right version of all dependencies to with "godep restore"
- All commands support golangs `...` notation - cool! so I can `godep update github.com/docker/...`

Hate:
- Once you've `restore`d there isn't a way to go back to the previous state so you end up with a load of projects in detached head state :disappointed: 
- So you have to set up a temporary $GOPATH *just* for handling dependencies
- Oh, and unless you use `save -r` which gives you REALLY long imports... You need to prefix every command with `godep`
- Which means you need to install `godep` on your build machines etc...

Pre 1.5, all deps will end up in `Godeps/_workspace/src/...`
The `godep go` command rewrites the $GOPATH to `Godeps/_workspace/src/...` so you get your vendored dependencies
 
With Go 1.5 the new `GO15VENDOREXPERIMENT=1` standardises on dependencies living in `./vendor` and looks there first. So no need to prefix every `go` command with `godep` - cool!

As more of a meta-point, we use it in `machine`, `distribution`, `libnetwork` and probably in other places too!

**Comment by thaJeztah** [comment]
Lots of discussion has been around using Godeps in docker/docker, see for reference https://github.com/docker/docker/pull/13756 (also contains suggestions for alternatives), and eventually closed in favor of https://github.com/docker/docker/pull/13783. No opinions from my side, just adding some history regarding this sensitive subject :smile:

**Comment by dave-tucker** [comment]
Thanks @thaJeztah

**Comment by dave-tucker** [comment]
Closing in favour of #48

**Pull request closed without merging**
