### PR TITLE
Remove vendored cuberite

### PR DESCRIPTION
**Pull request by dave-tucker**
We can download the latest version in the Dockerfile

Signed-off-by: Dave Tucker <dt@docker.com>

### CODE REVIEW

**Comment by gdevillele** [comment]
it works :+1: 
Q: don't we want to have control over the version of Cuberite?

**Comment by dave-tucker** [comment]
@gdevillele yeah we probably do - let me deconstruct their install script and see what I can do ;)

**Comment by dave-tucker** [comment]
...and it just grabs the latest build from Jenkins.
There hasn't been a github release since May and it's a pretty active project.
I'd suggest we stick with "latest" and pin it if we start seeing issues

**Comment by gdevillele** [comment]
LGTM 🦁

**Pull request merged**
