### PR TITLE
update dockercraft logo

### PR DESCRIPTION
**Pull request by gdevillele**
new logo with only 1 block on the whale's back.

Signed-off-by: Gaetan de Villele <gdevillele@gmail.com>

### CODE REVIEW

**Comment by gdevillele** [comment]
cc @dave-tucker @aduermael ✌️😎

some activity again!

**Comment by thaJeztah** [comment]
Does that mean new stickers will be printed? :heart:

**Comment by gdevillele** [comment]
Best idea of the day! 🐳
We should...

**Comment by thaJeztah** [comment]
Volunteering to beta test and review :innocent:

**Comment by gdevillele** [comment]
Haha! Thank you, it's noted! 👍

**Pull request merged**
