### PR TITLE
readme: correct spelling of 'Lua'

### PR DESCRIPTION
**Pull request by thibaultCha**
Very minor, but "Lua" should not be spelled in capitals, see: http://www.lua.org/about.html#name

Not sure if signing was required for such a commit but I did just in case.

Very fun project!

### CODE REVIEW

**Comment by toaster468** [comment]
:eggplant:

**Comment by aduermael** [comment]
I would prefer to merge #8 if that's ok with you @thibaultCha.
The diff is a bit cleaner without the added lines.

**Comment by thibaultCha** [comment]
You mean the removed lines? This has the advantage of cleaning trailing white spaces and blank lines. But it's fine with me.

**Comment by gdevillele** [comment]
👍

**Comment by aduermael** [comment]
@thibaultCha Oh, you're right, sorry a bit tired after this flight, back from Dockercon... 
LGTM

**Comment by thibaultCha** [comment]
Great then. Very jealous of your avatars btw.

**Pull request merged**
