### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by ricardotk**
Fix typos

### CODE REVIEW

**Comment by Seadragon91** [comment]
I think it makes more sense to make this pull request against [cuberite](https://github.com/cuberite/cuberite/), because they copied the plugins from there and the changes would be gone on next copy.

**Comment by ricardotk** [comment]
@Seadragon91 oh I didnt know that, let me just maintain the fix on README.md then

**Comment by gdevillele** [comment]
Thank you, @ricardotk !

@Seadragon91 , you are right, but a part of this PR concerns Dockercraft-specific files (like son.jua and tcpclient.lua)

**Comment by ricardotk** [comment]
@gdevillele Well, I think in this case I'll just maintain the PR as it is.

**Comment by ricardotk** [comment]
@gdevillele But for the copied plugins, have you guys ever considered using git submodules? maybe it could be a good choice for plugins that have a own repo, e.g. Core

**Comment by gdevillele** [comment]
Yes, you can leave the PR as-is. Feel free to submit PRs against the Cubrite repos for the fixes to last.
Using submodules is an option, absolutely. I am opening an issue for considering this, and updating Cubrite's version (this is long overdue 😕)

**Comment by dave-tucker** [comment]
@ricardotk ok, I've now removed all remnants of cuberite code from this repo.
It gets added at build time in the Dockerfile now.
If you could rebase to fix the typos in our code - which is now in `Docker/*.lua` that would be great!

**Comment by ricardotk** [comment]
@dave-tucker thanks!
I've uploaded a new version, only a few typos (:

**Comment by gdevillele** [comment]
Thank you :)

**Pull request merged**
