### PR TITLE
Updated README to include docker binary as per youtube video.

### PR DESCRIPTION
**Pull request by chrisdaish**
Noticed the Youtube video described mounting in the docker binary into the container, without this step I was not able to start/stop or create containers.

### CODE REVIEW

**Comment by aduermael** [comment]
This is an old video, we should do a new one. 
It should not be necessary to mount the docker binary anymore, the binary is added in the Dockerfile:
`ADD ./docker_linux_x64/docker /bin/docker`
It's far from being perfect though, this binary will work if you have the last version of Docker (1.9) installed on your host. We have to check other cases, and install the right binary.

But what you're describing works also, because it overrides the binary. 
The path won't always work though, depending on your environment the binary may be elsewhere. 
With Docker machine, I used to do something like:
`-v `machine ssh $(machine active) which docker`:/usr/local/bin/docker`

**Comment by chrisdaish** [comment]
This makes sense, I am running Docker 1.8.2.

Should the documentation present 2 different (version depending) run arguments, with and without the binary mount?

**Comment by aduermael** [comment]
To make it easier, we could `GET /version` from /var/run/docker.sock and install the right client in start.sh, depending on the answer.

**Comment by gdevillele** [comment]
This PR will be rejected, because we don't think that mounting the docker binary from the host is a good solution. (as you saw in the video, we used to do that, though)
We will keep the latest docker binary in the docker image, but prefix the API calls with the version of the daemon, as it is supported now.
I am creating an issue. :)

**Comment by aduermael** [comment]
#21 has been created to address this. Closing PR, thanks @chrisdaish!

**Pull request closed without merging**
